version: "3.5"
services:
  webapp:
    image: nginx:alpine
    container_name: videoplatform-webapp
    environment:
      - API_URL=http://172.16.238.12:3001
    volumes:
      - ./dist/video-platform-front:/usr/share/nginx/html:ro
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8082:80
    restart: unless-stopped
    external_links:
      - back
    networks:
      videoplatform-net:
        ipv4_address: 172.16.238.9

networks:
  videoplatform-net:
    external: true
    name: videoplatform-net
